import { cleanSubgenre } from "@/lib/catalogue";

export interface OfferRow {
  monetization: "flatrate" | "free" | "ads" | "rent" | "buy";
  /** PostgREST returns numerics as strings. */
  price: number | string | null;
  quality: string;
  url: string;
  providers: { name: string } | null;
}

export interface OfferEntry {
  name: string;
  url: string;
}

export interface PricedOffer extends OfferEntry {
  price: number | null;
}

export interface GroupedOffers {
  /** Subscription, free, and ad-supported services, one per provider. */
  stream: OfferEntry[];
  rent: PricedOffer[];
  buy: PricedOffer[];
}

const STREAMING = new Set<OfferRow["monetization"]>(["flatrate", "free", "ads"]);

function priceOf(offer: OfferRow): number | null {
  if (offer.price === null) return null;
  const value = Number(offer.price);
  return Number.isFinite(value) ? value : null;
}

function cheapest(offers: OfferRow[]): PricedOffer[] {
  const best = new Map<string, PricedOffer>();
  for (const offer of offers) {
    const name = offer.providers?.name;
    if (!name) continue;
    const price = priceOf(offer);
    const current = best.get(name);
    if (!current || (price !== null && (current.price === null || price < current.price))) best.set(name, { name, price, url: offer.url });
  }
  return [...best.values()].sort((a, b) => a.name.localeCompare(b.name, "en-US"));
}

/** One line per provider: streaming services first, then the cheapest rent and buy offers. */
export function groupOffers(offers: OfferRow[]): GroupedOffers {
  const stream = new Map<string, OfferEntry>();
  for (const offer of offers) {
    const name = offer.providers?.name;
    if (name && STREAMING.has(offer.monetization) && !stream.has(name)) stream.set(name, { name, url: offer.url });
  }
  return {
    stream: [...stream.values()].sort((a, b) => a.name.localeCompare(b.name, "en-US")),
    rent: cheapest(offers.filter((offer) => offer.monetization === "rent")),
    buy: cheapest(offers.filter((offer) => offer.monetization === "buy")),
  };
}

// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

/** A row of `movie_awards`: a Wikidata award record, usually attributed to a person. */
export interface AwardRow {
  award_name: string;
  result: "win" | "nominee";
  year: number | null;
  person_name: string | null;
  person_slug: string | null;
}

export interface AwardLine {
  text: string;
  detail: string;
}

export interface AwardSummary {
  lines: AwardLine[];
  /** Nominations left off the list once the limit is reached; wins are never hidden. */
  hiddenNominations: number;
}

interface AwardGroup {
  category: string;
  won: boolean;
  years: number[];
  people: Set<string>;
}

const ACADEMY_PREFIX = "Academy Award for ";
const NOMINATION_LIMIT = 5;

/** "Academy Award for Best Actor" is the category "Best Actor"; other award names stand alone. */
function categoryOf(awardName: string): string {
  return awardName.startsWith(ACADEMY_PREFIX) ? awardName.slice(ACADEMY_PREFIX.length) : awardName;
}

/** Wikidata leaves the person blank for awards that go to the film rather than to someone. */
function personOf(row: AwardRow): string {
  return (row.person_name ?? "").trim();
}

function winKey(category: string, person: string): string {
  return `${category} ${person}`;
}

/** Wikidata dates the same award differently across records, so a group keeps the year its rows agree on. */
function pickYear(years: number[]): number | null {
  const counts = new Map<number, number>();
  for (const year of years) counts.set(year, (counts.get(year) ?? 0) + 1);
  let best: number | null = null;
  let bestCount = 0;
  for (const [year, count] of counts) {
    if (count > bestCount || (count === bestCount && best !== null && year > best)) {
      best = year;
      bestCount = count;
    }
  }
  return best;
}

/** One group per category and outcome, so everyone who shared an award shares a line. */
function groupAwards(rows: AwardRow[]): AwardGroup[] {
  const wins = new Set(rows.filter((row) => row.result === "win").map((row) => winKey(categoryOf(row.award_name), personOf(row))));
  const groups = new Map<string, AwardGroup>();
  for (const row of rows) {
    const category = categoryOf(row.award_name);
    const person = personOf(row);
    if (row.result === "nominee" && wins.has(winKey(category, person))) continue;
    const key = `${category} ${row.result}`;
    const group = groups.get(key) ?? { category, won: row.result === "win", years: [], people: new Set<string>() };
    if (person) group.people.add(person);
    if (row.year !== null) group.years.push(row.year);
    groups.set(key, group);
  }
  return [...groups.values()].sort((a, b) => Number(b.won) - Number(a.won) || a.category.localeCompare(b.category, "en-US"));
}

function lineOf(group: AwardGroup): AwardLine {
  const people = [...group.people].sort((a, b) => a.localeCompare(b, "en-US")).join(", ");
  const year = pickYear(group.years);
  return {
    text: people ? `${group.category} ·\u00a0${people}` : group.category,
    detail: `${group.won ? "Won" : "Nominated"}${year ? `, ${year}` : ""}`,
  };
}

/**
 * Wins before nominations, each naming the category and the people it went to.
 *
 * Wikidata records a win as both a nomination and a win, so a person's nomination is dropped
 * once they won that category. Long nomination lists are cut to `nominationLimit` and counted.
 */
export function awardLines(rows: AwardRow[], nominationLimit = NOMINATION_LIMIT): AwardSummary {
  const lines: AwardLine[] = [];
  let listedNominations = 0;
  let hiddenNominations = 0;
  for (const group of groupAwards(rows)) {
    if (group.won) {
      lines.push(lineOf(group));
      continue;
    }
    if (listedNominations >= nominationLimit) {
      hiddenNominations += 1;
      continue;
    }
    listedNominations += 1;
    lines.push(lineOf(group));
  }
  return { lines, hiddenNominations };
}

export function imdbUrl(imdbId: string): string {
  return `https://www.imdb.com/title/${imdbId}/`;
}

/** The per-film row the detail popover requests. */
export interface FilmDetailRow {
  title: string;
  year: number | null;
  summary: string | null;
  justwatch_url: string | null;
  movie_imdb: { imdb_id: string; language: string | null; oscar_wins: number | null; oscar_nominations: number | null } | null;
  movie_genres: { genre_name: string }[];
  movie_subgenres: { subgenre_name: string }[];
  credits: { role: "director" | "writer" | "cast"; billing: number; person_slug: string; people: { name: string } | null }[];
  streaming_offers: OfferRow[];
}

export interface FilmDetailData {
  title: string;
  year: number | null;
  summary: string | null;
  directors: string[];
  language: string | null;
  subgenres: string[];
  oscars: { wins: number; nominations: number } | null;
  awards: AwardSummary;
  offers: GroupedOffers;
  imdbUrl: string | null;
  justwatchUrl: string | null;
}

/** Shapes the raw row into what the popover shows; subgenres drop labels that repeat a Metacritic genre. */
export function toFilmDetail(row: FilmDetailRow, awards: AwardRow[], genreNames: string[] = []): FilmDetailData {
  const genres = new Set([...row.movie_genres.map((entry) => entry.genre_name), ...genreNames].map((name) => name.toLocaleLowerCase("en-US")));
  const subgenres = [...new Set(row.movie_subgenres.map((entry) => cleanSubgenre(entry.subgenre_name)))]
    .filter((label) => !genres.has(label.toLocaleLowerCase("en-US")))
    .sort((a, b) => a.localeCompare(b, "en-US"));
  const directors = row.credits
    .filter((credit) => credit.role === "director")
    .sort((a, b) => a.billing - b.billing)
    .map((credit) => credit.people?.name ?? credit.person_slug);
  const imdb = row.movie_imdb;
  return {
    title: row.title,
    year: row.year,
    summary: row.summary,
    directors,
    language: imdb?.language ?? null,
    subgenres,
    oscars: imdb ? { wins: imdb.oscar_wins ?? 0, nominations: imdb.oscar_nominations ?? 0 } : null,
    awards: awardLines(awards),
    offers: groupOffers(row.streaming_offers),
    imdbUrl: imdb ? imdbUrl(imdb.imdb_id) : null,
    justwatchUrl: row.justwatch_url,
  };
}

/** "2 Oscars, 9 nominations", "Nominated for 3 Oscars", or null when there is nothing to say. */
export function oscarSummary(wins: number | null, nominations: number | null): string | null {
  if (wins && wins > 0) {
    const won = `${wins} Oscar${wins === 1 ? "" : "s"}`;
    return nominations && nominations > 0 ? `${won}, ${nominations} nomination${nominations === 1 ? "" : "s"}` : won;
  }
  if (nominations && nominations > 0) return `Nominated for ${nominations} Oscar${nominations === 1 ? "" : "s"}`;
  return null;
}
