// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

/**
 * DESIGN.md colour tokens as sRGB hex, because satori only reads sRGB.
 * Values are the OKLCH definitions from DESIGN.md converted at import time.
 */
export function oklchToHex(l: number, c: number, h: number): string {
	const a = c * Math.cos((h * Math.PI) / 180);
	const b = c * Math.sin((h * Math.PI) / 180);
	const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
	const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
	const s_ = l - 0.0894841775 * a - 1.291485548 * b;
	const l3 = l_ ** 3;
	const m3 = m_ ** 3;
	const s3 = s_ ** 3;
	const linear = [
		4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3,
		-1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3,
		-0.0041960863 * l3 - 0.7034186147 * m3 + 1.707614701 * s3,
	];
	const channel = (v: number) => {
		const clamped = Math.min(1, Math.max(0, v));
		const gamma =
			clamped <= 0.0031308
				? 12.92 * clamped
				: 1.055 * clamped ** (1 / 2.4) - 0.055;
		return Math.round(gamma * 255)
			.toString(16)
			.padStart(2, "0");
	};
	return `#${linear.map(channel).join("")}`;
}

export const color = {
	paper: oklchToHex(1, 0, 0),
	paperTint: oklchToHex(0.97, 0, 0),
	hairline: oklchToHex(0.922, 0, 0),
	pencilGray: oklchToHex(0.708, 0, 0),
	fadedInk: oklchToHex(0.556, 0, 0),
	ink: oklchToHex(0.145, 0, 0),
	chalk: oklchToHex(0.985, 0, 0),
	crimson: oklchToHex(0.525, 0.223, 3.958),
	litCrimson: oklchToHex(0.72, 0.19, 4),
	blushWhite: oklchToHex(0.971, 0.014, 343.198),
};

export const FONT_FAMILY = "Playfair Display";
