// Generated by OrchestKit Claude Plugin
// Created: 2026-09-12

import { join } from "node:path";

import { USER_AGENT } from "./types";

const MAX_ATTEMPTS = 4;

function cacheKey(url: string): string {
	return `${Bun.hash(url).toString(16)}.html`;
}

/**
 * Fetches a URL as text, reusing a cached copy when present and retrying
 * transient failures with exponential backoff.
 *
 * @throws Error when the page is a 404 or every attempt fails.
 */
export async function fetchHtml(
	url: string,
	cacheDir: string | null,
): Promise<string> {
	const cachePath = cacheDir ? join(cacheDir, cacheKey(url)) : null;
	if (cachePath) {
		const cached = Bun.file(cachePath);
		if (await cached.exists()) return cached.text();
	}

	let lastError = "";
	for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt += 1) {
		try {
			const response = await fetch(url, {
				headers: {
					"User-Agent": USER_AGENT,
					"Accept-Language": "en-US,en;q=0.9",
				},
			});
			if (response.ok) {
				const html = await response.text();
				if (cachePath) await Bun.write(cachePath, html);
				return html;
			}
			if (response.status === 404) throw new Error(`404 Not Found: ${url}`);
			lastError = `HTTP ${response.status}`;
		} catch (error) {
			if (error instanceof Error && error.message.startsWith("404"))
				throw error;
			lastError = error instanceof Error ? error.message : String(error);
		}
		await Bun.sleep(2 ** attempt * 1000);
	}
	throw new Error(
		`Failed to fetch ${url} after ${MAX_ATTEMPTS} attempts (${lastError})`,
	);
}
