// Generated by OrchestKit Claude Plugin
// Created: 2026-09-12

import type { Offer } from "./types";

/** Monetization buckets JustWatch reports, in the order most useful to a viewer. */
const BUCKETS = ["flatrate", "free", "ads", "rent", "buy"] as const;

interface RawOption {
	qualityType?: unknown;
	optionPrice?: unknown;
	optionCurrencyCode?: unknown;
}

interface RawOffer {
	providerId?: unknown;
	providerName?: unknown;
	providerIcon?: unknown;
	link?: unknown;
	monetization?: unknown;
	options?: unknown;
}

/**
 * Resolves Nuxt's flat payload into ordinary values.
 *
 * `__NUXT_DATA__` is devalue-encoded: every field holds an integer index into
 * one flat array rather than a value, which lets the payload share and cycle
 * references. Tagged entries (Date, Set, ...) are not needed here and resolve
 * to null.
 */
function hydrator(flat: unknown[]): (index: number) => unknown {
	const cache = new Map<number, unknown>();
	const resolve = (index: number): unknown => {
		if (index < 0) return undefined;
		if (cache.has(index)) return cache.get(index);
		const node = flat[index];
		if (node === null || typeof node !== "object") {
			cache.set(index, node);
			return node;
		}
		if (Array.isArray(node)) {
			if (typeof node[0] === "string") {
				cache.set(index, null);
				return null;
			}
			const list: unknown[] = [];
			cache.set(index, list);
			for (const ref of node as number[]) list.push(resolve(ref));
			return list;
		}
		const record: Record<string, unknown> = {};
		cache.set(index, record);
		for (const [key, ref] of Object.entries(node as Record<string, number>)) {
			record[key] = resolve(ref);
		}
		return record;
	};
	return resolve;
}

/**
 * Unwraps a JustWatch clickout URL to the destination it redirects to.
 *
 * The clickout carries ~600 characters of tracking context plus the real
 * target in `r`. Storing the target keeps rows small and sends viewers
 * straight to the provider.
 */
function destination(link: string): string {
	const target = new URL(link).searchParams.get("r");
	return target && /^https?:\/\//.test(target) ? target : link;
}

function readOffer(raw: RawOffer, monetization: string): Offer[] {
	const name = typeof raw.providerName === "string" ? raw.providerName : "";
	const link = typeof raw.link === "string" ? raw.link : "";
	const id = typeof raw.providerId === "number" ? raw.providerId : null;
	if (!name || !link || id === null) return [];

	const url = destination(link);
	const icon = typeof raw.providerIcon === "string" ? raw.providerIcon : null;
	const options = Array.isArray(raw.options)
		? (raw.options as RawOption[])
		: [];
	if (options.length === 0) {
		return [
			{
				provider_id: id,
				provider_name: name,
				provider_icon: icon,
				monetization,
				quality: "",
				price: null,
				currency_code: null,
				url,
			},
		];
	}
	return options.map((option) => ({
		provider_id: id,
		provider_name: name,
		provider_icon: icon,
		monetization,
		quality: typeof option.qualityType === "string" ? option.qualityType : "",
		price: typeof option.optionPrice === "number" ? option.optionPrice : null,
		currency_code:
			typeof option.optionCurrencyCode === "string"
				? option.optionCurrencyCode
				: null,
		url,
	}));
}

/** Keeps the cheapest row per provider, monetization and quality. */
function dedupe(offers: Offer[]): Offer[] {
	const best = new Map<string, Offer>();
	for (const offer of offers) {
		const key = `${offer.provider_id}|${offer.monetization}|${offer.quality}`;
		const seen = best.get(key);
		if (!seen || (offer.price ?? Infinity) < (seen.price ?? Infinity))
			best.set(key, offer);
	}
	return [...best.values()];
}

export interface WatchInfo {
	justwatch_url: string | null;
	offers: Offer[];
}

/**
 * Extracts streaming, rental and purchase options from a movie page.
 *
 * The rendered "Where to Watch" buttons carry no href — the destinations only
 * exist in the Nuxt payload — so this reads the payload rather than the DOM.
 */
export function parseWatchInfo(html: string): WatchInfo {
	const script =
		/<script[^>]*id="__NUXT_DATA__"[^>]*>([\s\S]*?)<\/script>/.exec(html);
	const justwatch = /href="(https:\/\/www\.justwatch\.com\/[^"]+)"/.exec(html);
	const info: WatchInfo = { justwatch_url: justwatch?.[1] ?? null, offers: [] };
	if (!script?.[1]) return info;

	let flat: unknown[];
	try {
		flat = JSON.parse(script[1]) as unknown[];
	} catch {
		return info;
	}
	if (!Array.isArray(flat)) return info;

	const index = flat.findIndex(
		(node) =>
			node !== null &&
			typeof node === "object" &&
			!Array.isArray(node) &&
			"hasOffers" in node,
	);
	if (index < 0) return info;

	const node = hydrator(flat)(index) as Record<string, unknown> | null;
	if (!node) return info;

	const offers: Offer[] = [];
	for (const bucket of BUCKETS) {
		const list = node[bucket];
		if (!Array.isArray(list)) continue;
		for (const raw of list as RawOffer[])
			offers.push(...readOffer(raw, bucket));
	}
	info.offers = dedupe(offers);
	return info;
}
