// Generated by OrchestKit Claude Plugin
// Created: 2026-09-12

import { mkdir } from "node:fs/promises";
import { join } from "node:path";

import type { CreditRole, ScrapedMovie } from "./types";

export type Format = "csv" | "json" | "both";

export interface MovieRow {
	id: number;
	slug: string;
	title: string;
	year: number | null;
	metascore: number | null;
	userscore: number | null;
	users_rated: number | null;
	summary: string | null;
	link: string;
	in_metascore_ranking: boolean;
	in_userscore_ranking: boolean;
}

export interface PersonRow {
	id: number;
	slug: string;
	name: string;
}

export interface CreditRow {
	movie_id: number;
	person_id: number;
	role: CreditRole;
	billing: number;
	character: string | null;
}

export interface GenreRow {
	id: number;
	name: string;
}

export interface MovieGenreRow {
	movie_id: number;
	genre_id: number;
}

export interface SeedTables {
	movies: MovieRow[];
	people: PersonRow[];
	credits: CreditRow[];
	genres: GenreRow[];
	movie_genres: MovieGenreRow[];
}

/**
 * Assigns 1-based ids to keys in sorted order.
 *
 * Sorting before numbering keeps ids stable across runs, so re-seeding a
 * database from a fresh scrape does not renumber unrelated rows.
 */
function index(keys: Iterable<string>): Map<string, number> {
	const sorted = [...new Set(keys)].sort();
	return new Map(sorted.map((key, position) => [key, position + 1]));
}

/** Splits scraped movies into normalized tables keyed by integer surrogate ids. */
export function buildTables(scraped: ScrapedMovie[]): SeedTables {
	const movieIds = index(scraped.map((movie) => movie.slug));
	const personIds = index(
		scraped.flatMap((movie) =>
			movie.credits.map((credit) => credit.person_slug),
		),
	);
	const genreIds = index(scraped.flatMap((movie) => movie.genres));

	const people = new Map<number, PersonRow>();
	const credits: CreditRow[] = [];
	const movieGenres: MovieGenreRow[] = [];

	for (const movie of scraped) {
		const movieId = movieIds.get(movie.slug)!;
		for (const name of movie.genres) {
			movieGenres.push({ movie_id: movieId, genre_id: genreIds.get(name)! });
		}

		const billing = { director: 0, writer: 0, cast: 0 };
		const seen = new Set<string>();
		for (const credit of movie.credits) {
			const personId = personIds.get(credit.person_slug)!;
			people.set(personId, {
				id: personId,
				slug: credit.person_slug,
				name: credit.name,
			});
			const key = `${personId}|${credit.role}`;
			if (seen.has(key)) continue;
			seen.add(key);
			billing[credit.role] += 1;
			credits.push({
				movie_id: movieId,
				person_id: personId,
				role: credit.role,
				billing: billing[credit.role],
				character: credit.character,
			});
		}
	}

	const movies = scraped.map((movie) => ({
		id: movieIds.get(movie.slug)!,
		slug: movie.slug,
		title: movie.title,
		year: movie.year,
		metascore: movie.metascore,
		userscore: movie.userscore,
		users_rated: movie.users_rated,
		summary: movie.summary,
		link: movie.link,
		in_metascore_ranking: movie.ranked_by.includes("metascore"),
		in_userscore_ranking: movie.ranked_by.includes("userscore"),
	}));

	return {
		movies: movies.sort((a, b) => a.id - b.id),
		people: [...people.values()].sort((a, b) => a.id - b.id),
		credits: credits.sort(
			(a, b) =>
				a.movie_id - b.movie_id ||
				a.role.localeCompare(b.role) ||
				a.billing - b.billing,
		),
		genres: [...genreIds]
			.map(([name, id]) => ({ id, name }))
			.sort((a, b) => a.id - b.id),
		movie_genres: movieGenres.sort(
			(a, b) => a.movie_id - b.movie_id || a.genre_id - b.genre_id,
		),
	};
}

/** Renders one CSV field, quoting per RFC 4180 and writing null as an empty field. */
function csvField(value: unknown): string {
	if (value === null || value === undefined) return "";
	const text = String(value);
	return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

function toCsv(rows: Record<string, unknown>[]): string {
	const first = rows[0];
	if (!first) return "";
	const columns = Object.keys(first);
	const lines = rows.map((row) =>
		columns.map((key) => csvField(row[key])).join(","),
	);
	return `${[columns.join(","), ...lines].join("\n")}\n`;
}

/** Writes each table to `dir` and returns the paths written. */
export async function writeTables(
	dir: string,
	tables: SeedTables,
	format: Format,
): Promise<string[]> {
	await mkdir(dir, { recursive: true });
	const written: string[] = [];
	for (const [name, rows] of Object.entries(tables)) {
		if (format !== "json") {
			const path = join(dir, `${name}.csv`);
			await Bun.write(path, toCsv(rows as Record<string, unknown>[]));
			written.push(`${path} (${rows.length} rows)`);
		}
		if (format !== "csv") {
			const path = join(dir, `${name}.json`);
			await Bun.write(path, `${JSON.stringify(rows, null, 2)}\n`);
			written.push(`${path} (${rows.length} rows)`);
		}
	}
	return written;
}
