// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

import { parseCsv } from "./wikidata";

const ENDPOINT = "https://query.wikidata.org/sparql";
const USER_AGENT = "movietable-scraper/1.0 (https://movietable.ai)";
const OSCAR = "wd:Q19020";

export interface AwardRow {
	imdb_id: string;
	award_name: string;
	result: "win" | "nominee";
	year: number | null;
	person_name: string;
}

/**
 * Awards credited to a person, found through the "for work" qualifier.
 *
 * Wikidata records an acting or writing nomination on the person's item, not
 * the film's, with P1686 pointing back at the film. Binding the film first
 * keeps the query selective enough to finish.
 */
function personQuery(ids: string[]): string {
	return `SELECT ?imdb ?result ?awardLabel ?personLabel ?year WHERE {
  VALUES ?imdb { ${ids.map((id) => `"${id}"`).join(" ")} }
  ?film wdt:P345 ?imdb .
  ?st pq:P1686 ?film .
  { ?person p:P166 ?st2 . FILTER(?st2 = ?st) ?st ps:P166 ?award . BIND("win" AS ?result) }
  UNION
  { ?person p:P1411 ?st2 . FILTER(?st2 = ?st) ?st ps:P1411 ?award . BIND("nominee" AS ?result) }
  ?award wdt:P31*/wdt:P279* ${OSCAR} .
  OPTIONAL { ?st pq:P585 ?when . BIND(YEAR(?when) AS ?year) }
  ?award rdfs:label ?awardLabel . FILTER(lang(?awardLabel)="en")
  ?person rdfs:label ?personLabel . FILTER(lang(?personLabel)="en")
}`;
}

/** Awards held by the film itself, such as Best Picture, which name no person. */
function filmQuery(ids: string[]): string {
	return `SELECT ?imdb ?result ?awardLabel ?year WHERE {
  VALUES ?imdb { ${ids.map((id) => `"${id}"`).join(" ")} }
  ?film wdt:P345 ?imdb .
  { ?film p:P166 ?st . ?st ps:P166 ?award . BIND("win" AS ?result) }
  UNION
  { ?film p:P1411 ?st . ?st ps:P1411 ?award . BIND("nominee" AS ?result) }
  ?award wdt:P31*/wdt:P279* ${OSCAR} .
  OPTIONAL { ?st pq:P585 ?when . BIND(YEAR(?when) AS ?year) }
  ?award rdfs:label ?awardLabel . FILTER(lang(?awardLabel)="en")
}`;
}

async function run(sparql: string): Promise<string[][]> {
	const response = await fetch(
		`${ENDPOINT}?query=${encodeURIComponent(sparql)}`,
		{
			headers: { Accept: "text/csv", "User-Agent": USER_AGENT },
		},
	);
	if (!response.ok) {
		throw new Error(
			`Wikidata HTTP ${response.status}: ${(await response.text()).slice(0, 160)}`,
		);
	}
	return parseCsv(await response.text());
}

function toRows(rows: string[][], withPerson: boolean): AwardRow[] {
	return rows.slice(1).flatMap((row) => {
		const [imdb, result, award, third, fourth] = row;
		if (!imdb || !award || (result !== "win" && result !== "nominee"))
			return [];
		const person = withPerson ? (third ?? "") : "";
		const year = Number(withPerson ? fourth : third);
		return [
			{
				imdb_id: imdb,
				award_name: award,
				result,
				year: Number.isFinite(year) && year > 0 ? year : null,
				person_name: person,
			},
		];
	});
}

interface Outcome {
	rows: AwardRow[];
	ok: boolean;
}

/**
 * Runs one query, distinguishing "no awards" from "the endpoint failed".
 *
 * The public endpoint returns 500/502/504/429 under load. Returning an empty
 * array on failure would be indistinguishable from a film that simply won
 * nothing, so failure is reported separately and the ids are retried later.
 */
async function attempt(
	sparql: string,
	withPerson: boolean,
	tries: number,
): Promise<Outcome> {
	for (let attemptNo = 0; attemptNo < tries; attemptNo += 1) {
		try {
			return { rows: toRows(await run(sparql), withPerson), ok: true };
		} catch {
			await Bun.sleep(2 ** attemptNo * 3000);
		}
	}
	return { rows: [], ok: false };
}

function merge(all: AwardRow[], people: AwardRow[], films: AwardRow[]): void {
	const covered = new Set(
		people.map((r) => `${r.imdb_id}|${r.award_name}|${r.result}`),
	);
	all.push(...people);
	for (const row of films) {
		if (!covered.has(`${row.imdb_id}|${row.award_name}|${row.result}`))
			all.push(row);
	}
}

/** Re-runs ids whose batch failed, in smaller slices that are likelier to complete. */
async function retryFailed(
	all: AwardRow[],
	failed: string[],
	size: number,
): Promise<string[]> {
	const stillFailed: string[] = [];
	for (let start = 0; start < failed.length; start += size) {
		const batch = failed.slice(start, start + size);
		const people = await attempt(personQuery(batch), true, 5);
		const films = await attempt(filmQuery(batch), false, 5);
		if (people.ok && films.ok) merge(all, people.rows, films.rows);
		else stillFailed.push(...batch);
		await Bun.sleep(1500);
	}
	return stillFailed;
}

/**
 * Collects Oscar wins and nominations per film, naming the person where the
 * category belongs to one.
 *
 * Film-level statements repeat many of the person-linked ones, so a film-level
 * row is kept only when no person-linked row already covers that category —
 * which is how Best Picture survives while Best Actor is not double counted.
 */
export async function collectAwards(
	ids: string[],
	batchSize: number,
	onProgress?: (done: number, total: number) => void,
): Promise<AwardRow[]> {
	const all: AwardRow[] = [];
	const failed: string[] = [];
	for (let start = 0; start < ids.length; start += batchSize) {
		const batch = ids.slice(start, start + batchSize);
		const people = await attempt(personQuery(batch), true, 3);
		const films = await attempt(filmQuery(batch), false, 3);
		if (people.ok && films.ok) merge(all, people.rows, films.rows);
		else failed.push(...batch);
		onProgress?.(Math.min(start + batchSize, ids.length), ids.length);
		await Bun.sleep(300);
	}

	if (failed.length > 0) {
		console.error(`  retrying ${failed.length} ids from failed batches...`);
		const remaining = await retryFailed(
			all,
			failed,
			Math.max(5, Math.floor(batchSize / 4)),
		);
		if (remaining.length > 0) {
			// Persist them: without the ids, an incomplete run cannot be topped up
			// later, because a film with no awards looks identical to one whose
			// query never succeeded.
			await Bun.write(
				".cache/imdb/unresolved-awards.json",
				JSON.stringify(remaining, null, 2),
			);
			console.error(
				`  ${remaining.length} ids still unresolved after retry; ` +
					"written to .cache/imdb/unresolved-awards.json",
			);
		} else {
			console.error("  retry recovered every failed id");
		}
	}

	const seen = new Set<string>();
	return all.filter((row) => {
		const key = `${row.imdb_id}|${row.award_name}|${row.result}|${row.person_name}`;
		if (seen.has(key)) return false;
		seen.add(key);
		return true;
	});
}
