// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

import { mkdir } from "node:fs/promises";
import { join } from "node:path";

/**
 * Per-id cache for Wikidata results.
 *
 * Queries are batched, but batch membership changes whenever the catalogue
 * grows, so caching whole responses would miss on every re-run. Caching each
 * id's rows separately means a later run only asks about ids it has never
 * resolved — which matters because the public endpoint rate-limits, and each
 * correctness fix so far has forced a full re-query of every id.
 *
 * A cached entry records that an id was resolved, including when it resolved
 * to nothing: absence of awards is a real answer and must not be re-queried.
 */
export class IdCache<T> {
	private readonly dir: string;
	private readonly memory = new Map<string, T>();

	constructor(root: string, name: string) {
		this.dir = join(root, name);
	}

	async load(): Promise<number> {
		await mkdir(this.dir, { recursive: true });
		const file = Bun.file(join(this.dir, "entries.json"));
		if (!(await file.exists())) return 0;
		try {
			const entries = (await file.json()) as [string, T][];
			for (const [key, value] of entries) this.memory.set(key, value);
		} catch {
			return 0;
		}
		return this.memory.size;
	}

	has(id: string): boolean {
		return this.memory.has(id);
	}

	get(id: string): T | undefined {
		return this.memory.get(id);
	}

	set(id: string, value: T): void {
		this.memory.set(id, value);
	}

	/** Returns the ids with no cached entry, in the order given. */
	missing(ids: string[]): string[] {
		return ids.filter((id) => !this.memory.has(id));
	}

	async save(): Promise<void> {
		await mkdir(this.dir, { recursive: true });
		await Bun.write(
			join(this.dir, "entries.json"),
			JSON.stringify([...this.memory]),
		);
	}
}
