// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

import { createReadStream } from "node:fs";
import { createInterface } from "node:readline";
import { createGunzip } from "node:zlib";

/** One candidate row from IMDb's published title.basics dataset. */
export interface TitleRow {
	tconst: string;
	titleType: string;
	primaryTitle: string;
	year: number | null;
	genres: string[];
}

export interface MovieKey {
	slug: string;
	title: string;
	year: number | null;
}

/** Title types worth matching a feature film against, best first. */
const TYPE_RANK = new Map([
	["movie", 0],
	["tvMovie", 1],
	["video", 2],
	["short", 3],
	["tvSpecial", 4],
]);

/**
 * Reduces a title to a comparison key.
 *
 * Metacritic and IMDb disagree on punctuation, diacritics, articles in
 * brackets and re-release suffixes, so those are stripped rather than
 * relied upon.
 */
export function normalizeTitle(title: string): string {
	return title
		.normalize("NFD")
		.replace(/[̀-ͯ]/g, "")
		.toLowerCase()
		.replace(/\((?:re-?release|\d{4})\)/g, "")
		.replace(/[^a-z0-9]+/g, " ")
		.trim();
}

/**
 * Streams title.basics.tsv.gz and keeps only rows whose title matches one we
 * are looking for.
 *
 * The uncompressed dataset is roughly 900 MB, so it is read line by line and
 * filtered against `wanted` instead of being indexed whole.
 */
export async function collectCandidates(
	datasetPath: string,
	wanted: Set<string>,
	onProgress?: (lines: number, kept: number) => void,
): Promise<Map<string, TitleRow[]>> {
	const found = new Map<string, TitleRow[]>();
	const stream = createReadStream(datasetPath).pipe(createGunzip());
	const lines = createInterface({ input: stream, crlfDelay: Infinity });

	let count = 0;
	let kept = 0;
	for await (const line of lines) {
		count += 1;
		if (count === 1) continue; // header
		// title.basics columns: 0 tconst, 1 titleType, 2 primaryTitle,
		// 3 originalTitle, 4 isAdult, 5 startYear, 6 endYear, 7 runtimeMinutes,
		// 8 genres. Indexed explicitly — counting elisions in a destructure got
		// this wrong once, silently reading endYear (always \N for films) as the
		// release year, which disabled year matching entirely.
		const cols = line.split("\t");
		const tconst = cols[0];
		const titleType = cols[1];
		const primaryTitle = cols[2];
		const originalTitle = cols[3];
		const startYear = cols[5];
		const genres = cols[8];
		if (!tconst || !titleType || !primaryTitle) continue;
		if (!TYPE_RANK.has(titleType)) continue;

		for (const candidate of new Set([primaryTitle, originalTitle ?? ""])) {
			if (!candidate) continue;
			const key = normalizeTitle(candidate);
			if (!wanted.has(key)) continue;
			const row: TitleRow = {
				tconst,
				titleType,
				primaryTitle,
				year: startYear && startYear !== "\\N" ? Number(startYear) : null,
				genres: genres && genres !== "\\N" ? genres.split(",") : [],
			};
			const list = found.get(key);
			if (list) list.push(row);
			else found.set(key, [row]);
			kept += 1;
			break;
		}
		if (count % 2_000_000 === 0) onProgress?.(count, kept);
	}
	onProgress?.(count, kept);
	return found;
}

/**
 * Picks the best candidate for one movie.
 *
 * Preference order is title type (a feature before a short), then closeness of
 * release year — Metacritic dates re-releases by their US re-release, so an
 * exact year match cannot be required — then the lowest tconst, which is
 * IMDb's own ordering and makes the choice deterministic.
 */
export function pickBest(
	movie: MovieKey,
	candidates: TitleRow[],
): TitleRow | null {
	if (candidates.length === 0) return null;
	const scored = [...candidates].sort((a, b) => {
		const type =
			(TYPE_RANK.get(a.titleType) ?? 9) - (TYPE_RANK.get(b.titleType) ?? 9);
		if (type !== 0) return type;
		if (movie.year !== null) {
			const da = a.year === null ? 999 : Math.abs(a.year - movie.year);
			const db = b.year === null ? 999 : Math.abs(b.year - movie.year);
			if (da !== db) return da - db;
		}
		return a.tconst.localeCompare(b.tconst);
	});
	return scored[0] ?? null;
}
