// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

const ENDPOINT = "https://query.wikidata.org/sparql";
const USER_AGENT = "movietable-scraper/1.0 (https://movietable.ai)";

/** Academy Award (Q19020); subclasses cover the individual categories. */
const OSCAR = "wd:Q19020";

export interface Enrichment {
	languages: string[];
	subgenres: string[];
	oscar_wins: number;
	oscar_nominations: number;
}

function query(ids: string[]): string {
	const values = ids.map((id) => `"${id}"`).join(" ");
	return `SELECT ?imdb
  (GROUP_CONCAT(DISTINCT ?langLabel; separator="|") AS ?languages)
  (GROUP_CONCAT(DISTINCT ?genreLabel; separator="|") AS ?subgenres)
  (COUNT(DISTINCT ?won) AS ?oscarWins)
  (COUNT(DISTINCT ?nom) AS ?oscarNoms)
WHERE {
  VALUES ?imdb { ${values} }
  ?film wdt:P345 ?imdb .
  OPTIONAL { ?film wdt:P364 ?l . ?l rdfs:label ?langLabel . FILTER(lang(?langLabel)="en") }
  OPTIONAL { ?film wdt:P136 ?g . ?g rdfs:label ?genreLabel . FILTER(lang(?genreLabel)="en") }
  OPTIONAL { ?film p:P166 ?won . ?won ps:P166 ?wa . ?wa wdt:P31*/wdt:P279* ${OSCAR} }
  OPTIONAL { ?film p:P1411 ?nom . ?nom ps:P1411 ?na . ?na wdt:P31*/wdt:P279* ${OSCAR} }
}
GROUP BY ?imdb`;
}

/** Parses an RFC 4180 CSV body into rows of fields. */
function parseCsv(body: string): string[][] {
	const rows: string[][] = [];
	let row: string[] = [];
	let field = "";
	let quoted = false;
	for (let i = 0; i < body.length; i += 1) {
		const char = body[i]!;
		if (quoted) {
			if (char !== '"') field += char;
			else if (body[i + 1] === '"') {
				field += '"';
				i += 1;
			} else quoted = false;
			continue;
		}
		if (char === '"') quoted = true;
		else if (char === ",") {
			row.push(field);
			field = "";
		} else if (char === "\n") {
			row.push(field);
			rows.push(row);
			row = [];
			field = "";
		} else if (char !== "\r") field += char;
	}
	if (field || row.length > 0) {
		row.push(field);
		rows.push(row);
	}
	return rows;
}

async function runBatch(ids: string[]): Promise<Map<string, Enrichment>> {
	const url = `${ENDPOINT}?query=${encodeURIComponent(query(ids))}`;
	const response = await fetch(url, {
		headers: { Accept: "text/csv", "User-Agent": USER_AGENT },
	});
	if (!response.ok) {
		throw new Error(
			`Wikidata HTTP ${response.status}: ${(await response.text()).slice(0, 200)}`,
		);
	}
	const rows = parseCsv(await response.text());
	const out = new Map<string, Enrichment>();
	for (const row of rows.slice(1)) {
		const [imdb, languages, subgenres, wins, noms] = row;
		if (!imdb) continue;
		out.set(imdb, {
			languages: languages ? languages.split("|").filter(Boolean) : [],
			subgenres: subgenres ? subgenres.split("|").filter(Boolean) : [],
			oscar_wins: Number(wins ?? 0) || 0,
			oscar_nominations: Number(noms ?? 0) || 0,
		});
	}
	return out;
}

/**
 * Looks up language, sub-genres and Oscar counts for IMDb ids.
 *
 * Queries are batched and retried; the public endpoint rate-limits, so a
 * failed batch backs off rather than being dropped.
 */
export async function enrich(
	ids: string[],
	batchSize: number,
	onProgress?: (done: number, total: number) => void,
): Promise<Map<string, Enrichment>> {
	const result = new Map<string, Enrichment>();
	for (let start = 0; start < ids.length; start += batchSize) {
		const batch = ids.slice(start, start + batchSize);
		let attempt = 0;
		for (;;) {
			try {
				for (const [key, value] of await runBatch(batch))
					result.set(key, value);
				break;
			} catch (error) {
				attempt += 1;
				if (attempt >= 4) {
					console.error(
						`  batch at ${start} failed: ${error instanceof Error ? error.message : String(error)}`,
					);
					break;
				}
				await Bun.sleep(2 ** attempt * 1000);
			}
		}
		onProgress?.(Math.min(start + batchSize, ids.length), ids.length);
		await Bun.sleep(200);
	}
	return result;
}
