// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

/**
 * Adds language, sub-genres and Oscar counts to the scraped catalogue.
 *
 * IMDb ids come from IMDb's published title.basics dataset, matched on title
 * and release year. The attributes come from Wikidata, keyed on that id.
 * Neither source involves crawling IMDb's title pages, which its robots.txt
 * disallows for automated clients.
 *
 * Usage:
 *   curl -o .cache/imdb/title.basics.tsv.gz https://datasets.imdbws.com/title.basics.tsv.gz
 *   bun run scripts/enrich-imdb.ts --dir seed
 */
import { parseArgs } from "node:util";

import {
	collectCandidates,
	type MovieKey,
	normalizeTitle,
	pickBest,
} from "./imdb/match";
import { enrich } from "./imdb/wikidata";
import { toCsv } from "./metacritic/seed";

interface MovieImdbRow {
	movie_slug: string;
	imdb_id: string;
	language: string | null;
	oscar_wins: number;
	oscar_nominations: number;
}

interface MovieSubgenreRow {
	movie_slug: string;
	subgenre_name: string;
}

async function writeTable(
	dir: string,
	name: string,
	rows: Record<string, unknown>[],
): Promise<void> {
	await Bun.write(`${dir}/${name}.csv`, toCsv(rows));
	await Bun.write(`${dir}/${name}.json`, `${JSON.stringify(rows, null, 2)}\n`);
	console.error(`  ${dir}/${name}.{csv,json} (${rows.length} rows)`);
}

async function main(): Promise<void> {
	const { values } = parseArgs({
		options: {
			dir: { type: "string", default: "seed" },
			dataset: { type: "string", default: ".cache/imdb/title.basics.tsv.gz" },
			batch: { type: "string", default: "150" },
		},
	});
	const batchSize = Number(values.batch);
	if (!Number.isInteger(batchSize) || batchSize < 1) {
		throw new RangeError(
			`--batch must be an integer >= 1, got ${values.batch}`,
		);
	}

	const movies: MovieKey[] = await Bun.file(`${values.dir}/movies.json`).json();
	const wanted = new Set(movies.map((movie) => normalizeTitle(movie.title)));
	console.error(
		`matching ${movies.length} movies (${wanted.size} distinct titles)...`,
	);

	const candidates = await collectCandidates(
		values.dataset,
		wanted,
		(lines, kept) =>
			console.error(
				`  scanned ${(lines / 1e6).toFixed(1)}M rows, ${kept} candidates`,
			),
	);

	const matched: MovieImdbRow[] = [];
	const unmatched: string[] = [];
	const byId = new Map<string, string>();
	for (const movie of movies) {
		const best = pickBest(
			movie,
			candidates.get(normalizeTitle(movie.title)) ?? [],
		);
		if (!best) {
			unmatched.push(movie.slug);
			continue;
		}
		byId.set(best.tconst, movie.slug);
		matched.push({
			movie_slug: movie.slug,
			imdb_id: best.tconst,
			language: null,
			oscar_wins: 0,
			oscar_nominations: 0,
		});
	}
	console.error(
		`matched ${matched.length}/${movies.length} (${unmatched.length} unmatched)`,
	);

	const ids = [...new Set(matched.map((row) => row.imdb_id))];
	console.error(`enriching ${ids.length} ids from Wikidata...`);
	const enriched = await enrich(ids, batchSize, (done, total) => {
		if (done % (batchSize * 5) === 0 || done === total)
			console.error(`  ${done}/${total}`);
	});

	const subgenres = new Set<string>();
	const movieSubgenres: MovieSubgenreRow[] = [];
	for (const row of matched) {
		const found = enriched.get(row.imdb_id);
		if (!found) continue;
		// "Accept the first match" for language: Wikidata lists the original
		// language first for multilingual films.
		row.language = found.languages[0] ?? null;
		row.oscar_wins = found.oscar_wins;
		row.oscar_nominations = found.oscar_nominations;
		for (const name of found.subgenres) {
			subgenres.add(name);
			movieSubgenres.push({ movie_slug: row.movie_slug, subgenre_name: name });
		}
	}

	matched.sort((a, b) => a.movie_slug.localeCompare(b.movie_slug));
	movieSubgenres.sort(
		(a, b) =>
			a.movie_slug.localeCompare(b.movie_slug) ||
			a.subgenre_name.localeCompare(b.subgenre_name),
	);

	await writeTable(
		values.dir,
		"movie_imdb",
		matched as unknown as Record<string, unknown>[],
	);
	await writeTable(
		values.dir,
		"subgenres",
		[...subgenres].sort().map((name) => ({ name })),
	);
	await writeTable(
		values.dir,
		"movie_subgenres",
		movieSubgenres as unknown as Record<string, unknown>[],
	);

	const withLanguage = matched.filter((row) => row.language).length;
	const withOscars = matched.filter(
		(row) => row.oscar_wins + row.oscar_nominations > 0,
	).length;
	console.error(
		`\nlanguage on ${withLanguage}, sub-genres on ${new Set(movieSubgenres.map((r) => r.movie_slug)).size}, ` +
			`Oscar activity on ${withOscars} of ${matched.length}`,
	);
}

if (import.meta.main) await main();
