// Generated by OrchestKit Claude Plugin
// Created: 2026-09-13

/**
 * Adds language, sub-genres and Oscar counts to the scraped catalogue.
 *
 * IMDb ids come from IMDb's published title.basics dataset, matched on title
 * and release year. The attributes come from Wikidata, keyed on that id.
 * Neither source involves crawling IMDb's title pages, which its robots.txt
 * disallows for automated clients.
 *
 * Usage:
 *   curl -o .cache/imdb/title.basics.tsv.gz https://datasets.imdbws.com/title.basics.tsv.gz
 *   bun run scripts/enrich-imdb.ts --dir seed
 */
import { parseArgs } from "node:util";
import { collectAwards } from "./imdb/awards";
import {
	collectCandidates,
	type MovieKey,
	normalizeTitle,
	pickBest,
} from "./imdb/match";
import { enrich } from "./imdb/wikidata";
import { toCsv } from "./metacritic/seed";

interface MovieAwardRow {
	movie_slug: string;
	award_name: string;
	result: string;
	year: number | null;
	person_name: string;
	person_slug: string | null;
}

/**
 * Indexes each film's credited people by lowercased name.
 *
 * Wikidata names an honoree but identifies them by its own id, which does not
 * match Metacritic's person slug. Restricting the name match to people already
 * credited on that same film keeps it precise.
 */
async function creditedPeople(
	dir: string,
): Promise<Map<string, Map<string, string>>> {
	const credits: { movie_slug: string; person_slug: string }[] = await Bun.file(
		`${dir}/credits.json`,
	).json();
	const people: { slug: string; name: string }[] = await Bun.file(
		`${dir}/people.json`,
	).json();
	const nameBySlug = new Map(
		people.map((person) => [person.slug, person.name.toLowerCase()]),
	);
	const byMovie = new Map<string, Map<string, string>>();
	for (const credit of credits) {
		const name = nameBySlug.get(credit.person_slug);
		if (!name) continue;
		const forMovie =
			byMovie.get(credit.movie_slug) ?? new Map<string, string>();
		forMovie.set(name, credit.person_slug);
		byMovie.set(credit.movie_slug, forMovie);
	}
	return byMovie;
}

interface MovieImdbRow {
	movie_slug: string;
	imdb_id: string;
	/**
	 * Release year of the matched IMDb title.
	 *
	 * Kept so a match can be audited: the sources disagree on titles often
	 * enough that a large gap against movies.year flags a likely wrong match.
	 */
	imdb_year: number | null;
	language: string | null;
	oscar_wins: number;
	oscar_nominations: number;
}

interface MovieSubgenreRow {
	movie_slug: string;
	subgenre_name: string;
}

async function writeTable(
	dir: string,
	name: string,
	rows: Record<string, unknown>[],
): Promise<void> {
	await Bun.write(`${dir}/${name}.csv`, toCsv(rows));
	await Bun.write(`${dir}/${name}.json`, `${JSON.stringify(rows, null, 2)}\n`);
	console.error(`  ${dir}/${name}.{csv,json} (${rows.length} rows)`);
}

async function main(): Promise<void> {
	const { values } = parseArgs({
		options: {
			dir: { type: "string", default: "seed" },
			dataset: { type: "string", default: ".cache/imdb/title.basics.tsv.gz" },
			batch: { type: "string", default: "150" },
		},
	});
	const batchSize = Number(values.batch);
	if (!Number.isInteger(batchSize) || batchSize < 1) {
		throw new RangeError(
			`--batch must be an integer >= 1, got ${values.batch}`,
		);
	}

	const movies: MovieKey[] = await Bun.file(`${values.dir}/movies.json`).json();
	const wanted = new Set(movies.map((movie) => normalizeTitle(movie.title)));
	console.error(
		`matching ${movies.length} movies (${wanted.size} distinct titles)...`,
	);

	const candidates = await collectCandidates(
		values.dataset,
		wanted,
		(lines, kept) =>
			console.error(
				`  scanned ${(lines / 1e6).toFixed(1)}M rows, ${kept} candidates`,
			),
	);

	const matched: MovieImdbRow[] = [];
	const unmatched: string[] = [];
	const byId = new Map<string, string>();
	for (const movie of movies) {
		const best = pickBest(
			movie,
			candidates.get(normalizeTitle(movie.title)) ?? [],
		);
		if (!best) {
			unmatched.push(movie.slug);
			continue;
		}
		byId.set(best.tconst, movie.slug);
		matched.push({
			movie_slug: movie.slug,
			imdb_id: best.tconst,
			imdb_year: best.year,
			language: null,
			oscar_wins: 0,
			oscar_nominations: 0,
		});
	}
	console.error(
		`matched ${matched.length}/${movies.length} (${unmatched.length} unmatched)`,
	);

	const ids = [...new Set(matched.map((row) => row.imdb_id))];
	console.error(`enriching ${ids.length} ids from Wikidata...`);
	const enriched = await enrich(ids, batchSize, (done, total) => {
		if (done % (batchSize * 5) === 0 || done === total)
			console.error(`  ${done}/${total}`);
	});

	const subgenres = new Set<string>();
	const movieSubgenres: MovieSubgenreRow[] = [];
	for (const row of matched) {
		const found = enriched.get(row.imdb_id);
		if (!found) continue;
		// "Accept the first match" for language: Wikidata lists the original
		// language first for multilingual films.
		row.language = found.languages[0] ?? null;
		for (const name of found.subgenres) {
			subgenres.add(name);
			movieSubgenres.push({ movie_slug: row.movie_slug, subgenre_name: name });
		}
	}

	console.error(`collecting Oscar categories for ${ids.length} ids...`);
	const rawAwards = await collectAwards(ids, 40, (done, total) => {
		if (done % 400 === 0 || done === total) console.error(`  ${done}/${total}`);
	});

	const credited = await creditedPeople(values.dir);
	const awards: MovieAwardRow[] = [];
	for (const award of rawAwards) {
		const slug = byId.get(award.imdb_id);
		if (!slug) continue;
		const person = award.person_name
			? (credited.get(slug)?.get(award.person_name.toLowerCase()) ?? null)
			: null;
		awards.push({
			movie_slug: slug,
			award_name: award.award_name,
			result: award.result,
			year: award.year,
			person_name: award.person_name,
			person_slug: person,
		});
	}

	// Keep the counts consistent with the categories rather than with a second,
	// separately-aggregated query.
	// Count distinct categories, not rows. A category credited to several people
	// produces a row each — Best Sound on Star Wars names four engineers — but
	// the film won one Oscar for it.
	const tally = new Map<string, { wins: Set<string>; noms: Set<string> }>();
	for (const award of awards) {
		const seen = tally.get(award.movie_slug) ?? {
			wins: new Set(),
			noms: new Set(),
		};
		if (award.result === "win") seen.wins.add(award.award_name);
		else seen.noms.add(award.award_name);
		tally.set(award.movie_slug, seen);
	}
	for (const row of matched) {
		const seen = tally.get(row.movie_slug);
		row.oscar_wins = seen?.wins.size ?? 0;
		row.oscar_nominations = seen?.noms.size ?? 0;
	}

	awards.sort(
		(a, b) =>
			a.movie_slug.localeCompare(b.movie_slug) ||
			a.result.localeCompare(b.result) ||
			a.award_name.localeCompare(b.award_name) ||
			a.person_name.localeCompare(b.person_name),
	);

	matched.sort((a, b) => a.movie_slug.localeCompare(b.movie_slug));
	movieSubgenres.sort(
		(a, b) =>
			a.movie_slug.localeCompare(b.movie_slug) ||
			a.subgenre_name.localeCompare(b.subgenre_name),
	);

	await writeTable(
		values.dir,
		"movie_imdb",
		matched as unknown as Record<string, unknown>[],
	);
	await writeTable(
		values.dir,
		"subgenres",
		[...subgenres].sort().map((name) => ({ name })),
	);
	await writeTable(
		values.dir,
		"movie_subgenres",
		movieSubgenres as unknown as Record<string, unknown>[],
	);
	await writeTable(
		values.dir,
		"movie_awards",
		awards as unknown as Record<string, unknown>[],
	);

	const withLanguage = matched.filter((row) => row.language).length;
	const withOscars = matched.filter(
		(row) => row.oscar_wins + row.oscar_nominations > 0,
	).length;
	const named = awards.filter((row) => row.person_name).length;
	const linked = awards.filter((row) => row.person_slug).length;
	console.error(
		`\nlanguage on ${withLanguage}, sub-genres on ${new Set(movieSubgenres.map((r) => r.movie_slug)).size}, ` +
			`Oscar activity on ${withOscars} of ${matched.length}`,
	);
	console.error(
		`${awards.length} award rows; ${named} name a person, ${linked} link to a credited person`,
	);
}

if (import.meta.main) await main();
