// Generated by OrchestKit Claude Plugin
// Created: 2026-09-12

/**
 * Loads the scraped seed tables into Supabase over PostgREST.
 *
 * Uses the REST endpoint rather than a direct Postgres connection so it works
 * against a deployment that only exposes HTTPS. Rows are upserted on their
 * primary key, so re-running is idempotent. Apply the schema migration in
 * supabase/migrations first — PostgREST cannot create tables.
 *
 * Reads SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY from the environment
 * (Bun loads .env automatically).
 *
 * Usage: bun run scripts/seed-supabase.ts --dir seed --batch 500
 */
import { parseArgs } from "node:util";

/** Insert order matters: referenced tables first, so foreign keys resolve. */
const TABLES = [
	"movies",
	"people",
	"genres",
	"credits",
	"movie_genres",
] as const;

type TableName = (typeof TABLES)[number];

/** Conflict targets matching each table's primary key. */
const CONFLICT_KEYS: Record<TableName, string> = {
	movies: "id",
	people: "id",
	genres: "id",
	credits: "movie_id,person_id,role",
	movie_genres: "movie_id,genre_id",
};

function requireEnv(name: string): string {
	const value = process.env[name];
	if (!value) {
		throw new Error(
			`${name} is not set. Add it to .env or export it before running.`,
		);
	}
	return value;
}

async function upsertBatch(
	url: string,
	key: string,
	table: TableName,
	rows: unknown[],
): Promise<void> {
	const endpoint = `${url}/rest/v1/${table}?on_conflict=${CONFLICT_KEYS[table]}`;
	const response = await fetch(endpoint, {
		method: "POST",
		headers: {
			apikey: key,
			Authorization: `Bearer ${key}`,
			"Content-Type": "application/json",
			Prefer: "resolution=merge-duplicates,return=minimal",
		},
		body: JSON.stringify(rows),
	});
	if (!response.ok) {
		const detail = (await response.text()).slice(0, 500);
		throw new Error(
			`${table}: HTTP ${response.status} ${response.statusText} — ${detail}`,
		);
	}
}

async function seedTable(
	url: string,
	key: string,
	table: TableName,
	dir: string,
	batchSize: number,
): Promise<number> {
	const rows: unknown[] = await Bun.file(`${dir}/${table}.json`).json();
	for (let start = 0; start < rows.length; start += batchSize) {
		await upsertBatch(url, key, table, rows.slice(start, start + batchSize));
		const done = Math.min(start + batchSize, rows.length);
		console.error(`  ${table}: ${done}/${rows.length}`);
	}
	return rows.length;
}

async function countRows(
	url: string,
	key: string,
	table: TableName,
): Promise<string> {
	const response = await fetch(`${url}/rest/v1/${table}?select=*&limit=1`, {
		headers: {
			apikey: key,
			Authorization: `Bearer ${key}`,
			Prefer: "count=exact",
		},
	});
	if (!response.ok) return `HTTP ${response.status}`;
	return response.headers.get("content-range")?.split("/").pop() ?? "unknown";
}

async function main(): Promise<void> {
	const { values } = parseArgs({
		options: {
			dir: { type: "string", default: "seed" },
			batch: { type: "string", default: "500" },
		},
	});
	const batchSize = Number(values.batch);
	if (!Number.isInteger(batchSize) || batchSize < 1) {
		throw new RangeError(
			`--batch must be an integer >= 1, got ${values.batch}`,
		);
	}

	const url = requireEnv("SUPABASE_URL").replace(/\/+$/, "");
	const key = requireEnv("SUPABASE_SERVICE_ROLE_KEY");

	for (const table of TABLES) {
		const total = await seedTable(url, key, table, values.dir, batchSize);
		console.error(`${table}: ${total} rows sent`);
	}

	console.error("\nrow counts reported by the database:");
	for (const table of TABLES) {
		console.error(`  ${table}: ${await countRows(url, key, table)}`);
	}
}

if (import.meta.main) await main();
