-- Generated by OrchestKit Claude Plugin
-- Created: 2026-09-13

-- Language, sub-genres and Oscar counts for the catalogue.
--
-- IMDb ids come from IMDb's published title.basics dataset, matched on title
-- and release year; the attributes come from Wikidata keyed on that id.
--
-- imdb_id is deliberately not unique: Metacritic lists some films twice (an
-- original and its re-release), and both resolve to the same IMDb title.

create table movie_imdb (
  movie_slug text primary key references movies (slug) on delete cascade,
  imdb_id text not null,
  language text,
  oscar_wins integer not null default 0 check (oscar_wins >= 0),
  oscar_nominations integer not null default 0 check (oscar_nominations >= 0)
);

comment on table movie_imdb is
  'Attributes resolved via IMDb id. Oscar counts come from Wikidata and its award coverage is incomplete — treat them as indicative, not authoritative.';
comment on column movie_imdb.language is
  'Original language. Multilingual films list several in Wikidata; the first is kept.';

create table subgenres (
  name text primary key
);

comment on table subgenres is 'Wikidata film genres, finer-grained than the genres Metacritic assigns.';

create table movie_subgenres (
  movie_slug text not null references movies (slug) on delete cascade,
  subgenre_name text not null references subgenres (name) on delete cascade,
  primary key (movie_slug, subgenre_name)
);

create index movie_imdb_imdb_id_idx on movie_imdb (imdb_id);
create index movie_imdb_language_idx on movie_imdb (language);
create index movie_imdb_oscar_wins_idx on movie_imdb (oscar_wins desc);
create index movie_subgenres_subgenre_name_idx on movie_subgenres (subgenre_name);

alter table movie_imdb enable row level security;
alter table subgenres enable row level security;
alter table movie_subgenres enable row level security;

create policy "movie imdb data is publicly readable" on movie_imdb for select using (true);
create policy "subgenres are publicly readable" on subgenres for select using (true);
create policy "movie_subgenres are publicly readable" on movie_subgenres for select using (true);
