-- Generated by OrchestKit Claude Plugin
-- Created: 2026-09-13

-- Individual Oscar categories, naming the honoree where the category has one.
--
-- Wikidata records acting and writing nominations on the person's item with a
-- "for work" qualifier pointing at the film, and film-level honours such as
-- Best Picture on the film itself. Both end up here; person_name is '' for the
-- film-level ones so the primary key stays non-null.
--
-- A film can appear several times in one category: The Godfather has three
-- Best Supporting Actor nominations, one each for Caan, Duvall and Pacino.
-- Including person_name in the key preserves that.

create table movie_awards (
  movie_slug text not null references movies (slug) on delete cascade,
  award_name text not null,
  result text not null check (result in ('win', 'nominee')),
  year integer,
  person_name text not null default '',
  -- Set when the honoree is also credited on that film in our own data;
  -- Wikidata identifies people by its own ids, which Metacritic does not share.
  person_slug text references people (slug) on delete set null,
  primary key (movie_slug, award_name, result, person_name)
);

comment on table movie_awards is
  'Oscar categories from Wikidata. Its award coverage is incomplete, so treat these as indicative.';

create index movie_awards_result_idx on movie_awards (result);
create index movie_awards_award_name_idx on movie_awards (award_name);
create index movie_awards_person_slug_idx on movie_awards (person_slug);

alter table movie_awards enable row level security;

create policy "movie awards are publicly readable" on movie_awards for select using (true);
