-- Generated by OrchestKit Claude Plugin
-- Created: 2026-09-12

-- Where to watch each movie, from the JustWatch data embedded in Metacritic's
-- page payload.

alter table movies add column justwatch_url text;

comment on column movies.justwatch_url is
  'JustWatch page listing every option, including any this table does not carry.';

create table providers (
  id integer primary key,
  name text not null,
  icon_url text
);

comment on table providers is 'Streaming, rental and purchase services, keyed on JustWatch provider ids.';

create table streaming_offers (
  movie_id integer not null references movies (id) on delete cascade,
  provider_id integer not null references providers (id) on delete cascade,
  -- flatrate = included with a subscription; free and ads need no payment.
  monetization text not null check (monetization in ('flatrate', 'free', 'ads', 'rent', 'buy')),
  -- '' when the site quotes no specific quality, so the key stays non-null.
  quality text not null default '',
  url text not null,
  price numeric(8, 2) check (price >= 0),
  currency_code text,
  primary key (movie_id, provider_id, monetization, quality)
);

comment on column streaming_offers.url is
  'Link straight to the provider, unwrapped from JustWatch''s tracking redirect.';

create index streaming_offers_provider_id_idx on streaming_offers (provider_id);
create index streaming_offers_monetization_idx on streaming_offers (monetization);

alter table providers enable row level security;
alter table streaming_offers enable row level security;

create policy "providers are publicly readable" on providers for select using (true);
create policy "streaming offers are publicly readable" on streaming_offers for select using (true);
