-- Generated by OrchestKit Claude Plugin
-- Created: 2026-09-13

-- Release year of the matched IMDb title, kept so a match can be audited.
--
-- Metacritic and IMDb name films differently often enough that title matching
-- can land on the wrong entry: IMDb calls the 2021 Dune "Dune: Part One", so a
-- search for "Dune" cannot see it and settles on an unrelated 1989 film of that
-- name. Storing the matched title's year makes that visible — a large gap
-- against movies.year flags a match worth distrusting — instead of leaving a
-- wrong row indistinguishable from a right one.

alter table movie_imdb add column imdb_year integer;

comment on column movie_imdb.imdb_year is
  'Release year of the matched IMDb title. A wide gap against movies.year suggests a mis-match; note that Metacritic dates re-releases by their US re-release, so some gaps are legitimate.';

create index movie_imdb_imdb_year_idx on movie_imdb (imdb_year);
