-- Generated by OrchestKit Claude Plugin
-- Created: 2026-09-13

-- Re-key the catalogue on the identifiers the sources already own.
--
-- The previous schema used integer ids minted by the scraper from the sorted
-- natural keys. Those are reproducible for a given scrape but not stable across
-- scrapes: growing the set from 1,506 to 3,040 movies repointed 1,504 of the
-- 1,506 existing ids at a different film. Metacritic's movie and person slugs,
-- the genre name and JustWatch's provider id do not move, so an upsert keyed on
-- them stays correct however the dataset grows.
--
-- The tables are recreated empty and reloaded from seed/. The catalogue is
-- unavailable between this migration and the end of that load.

drop table if exists streaming_offers;
drop table if exists movie_genres;
drop table if exists credits;
drop table if exists providers;
drop table if exists genres;
drop table if exists movies;
drop table if exists people;

create table movies (
  slug text primary key,
  title text not null,
  year integer,
  metascore integer check (metascore between 0 and 100),
  userscore numeric(4, 1) check (userscore between 0 and 100),
  users_rated integer check (users_rated >= 0),
  summary text,
  link text not null,
  justwatch_url text,
  in_metascore_ranking boolean not null default false,
  in_userscore_ranking boolean not null default false
);

comment on column movies.slug is 'Metacritic identifier from /movie/<slug>/.';
comment on column movies.userscore is
  'Metacritic user score rescaled from its 0-10 display to 0-100, so it shares units with metascore.';
comment on column movies.justwatch_url is
  'JustWatch page listing every option, including any streaming_offers does not carry.';

create table people (
  slug text primary key,
  name text not null
);

comment on column people.slug is
  'Metacritic identifier from /person/<slug>/. Names are not unique; slugs are.';

create table genres (
  name text primary key
);

create table providers (
  id integer primary key,
  name text not null,
  icon_url text
);

comment on table providers is 'Streaming, rental and purchase services, keyed on JustWatch provider ids.';

create table credits (
  movie_slug text not null references movies (slug) on delete cascade,
  person_slug text not null references people (slug) on delete cascade,
  role credit_role not null,
  billing integer not null check (billing > 0),
  "character" text,
  primary key (movie_slug, person_slug, role)
);

comment on column credits.billing is 'Order the site lists this person in, within its role.';
comment on column credits."character" is 'Role played, for cast credits only.';

create table movie_genres (
  movie_slug text not null references movies (slug) on delete cascade,
  genre_name text not null references genres (name) on delete cascade,
  primary key (movie_slug, genre_name)
);

create table streaming_offers (
  movie_slug text not null references movies (slug) on delete cascade,
  provider_id integer not null references providers (id) on delete cascade,
  -- flatrate = included with a subscription; free and ads need no payment.
  monetization text not null check (monetization in ('flatrate', 'free', 'ads', 'rent', 'buy')),
  -- '' when the site quotes no specific quality, so the key stays non-null.
  quality text not null default '',
  url text not null,
  price numeric(8, 2) check (price >= 0),
  currency_code text,
  primary key (movie_slug, provider_id, monetization, quality)
);

comment on column streaming_offers.url is
  'Link straight to the provider, unwrapped from JustWatch''s tracking redirect.';

create index credits_person_slug_idx on credits (person_slug);
create index credits_role_idx on credits (role);
create index movie_genres_genre_name_idx on movie_genres (genre_name);
create index movies_metascore_idx on movies (metascore desc);
create index movies_userscore_idx on movies (userscore desc);
create index movies_year_idx on movies (year);
create index streaming_offers_provider_id_idx on streaming_offers (provider_id);
create index streaming_offers_monetization_idx on streaming_offers (monetization);

alter table movies enable row level security;
alter table people enable row level security;
alter table genres enable row level security;
alter table providers enable row level security;
alter table credits enable row level security;
alter table movie_genres enable row level security;
alter table streaming_offers enable row level security;

create policy "movies are publicly readable" on movies for select using (true);
create policy "people are publicly readable" on people for select using (true);
create policy "genres are publicly readable" on genres for select using (true);
create policy "providers are publicly readable" on providers for select using (true);
create policy "credits are publicly readable" on credits for select using (true);
create policy "movie_genres are publicly readable" on movie_genres for select using (true);
create policy "streaming offers are publicly readable" on streaming_offers for select using (true);
