-- Generated by OrchestKit Claude Plugin
-- Created: 2026-09-12

-- Movie catalogue scraped from Metacritic.
--
-- Ids are assigned by scripts/scrape-metacritic.ts from the sorted natural keys
-- (movie slug, person slug, genre name), so a re-scrape reproduces them. They
-- are therefore written explicitly rather than generated by the database.

create type credit_role as enum ('director', 'writer', 'cast');

create table movies (
  id integer primary key,
  slug text not null unique,
  title text not null,
  year integer,
  metascore integer check (metascore between 0 and 100),
  userscore numeric(4, 1) check (userscore between 0 and 100),
  users_rated integer check (users_rated >= 0),
  summary text,
  link text not null,
  in_metascore_ranking boolean not null default false,
  in_userscore_ranking boolean not null default false
);

comment on column movies.userscore is
  'Metacritic user score rescaled from its 0-10 display to 0-100, so it shares units with metascore.';
comment on column movies.users_rated is 'Number of user ratings behind userscore.';

create table people (
  id integer primary key,
  slug text not null unique,
  name text not null
);

comment on column people.slug is
  'Metacritic person identifier from /person/<slug>/. Names are not unique; slugs are.';

create table genres (
  id integer primary key,
  name text not null unique
);

create table credits (
  movie_id integer not null references movies (id) on delete cascade,
  person_id integer not null references people (id) on delete cascade,
  role credit_role not null,
  billing integer not null check (billing > 0),
  "character" text,
  primary key (movie_id, person_id, role)
);

comment on column credits.billing is 'Order the site lists this person in, within its role.';
comment on column credits."character" is 'Role played, for cast credits only.';

create table movie_genres (
  movie_id integer not null references movies (id) on delete cascade,
  genre_id integer not null references genres (id) on delete cascade,
  primary key (movie_id, genre_id)
);

create index credits_person_id_idx on credits (person_id);
create index credits_role_idx on credits (role);
create index movie_genres_genre_id_idx on movie_genres (genre_id);
create index movies_metascore_idx on movies (metascore desc);
create index movies_userscore_idx on movies (userscore desc);
create index movies_year_idx on movies (year);

-- The catalogue is public reference data: readable by anyone, writable only by
-- the service role, which bypasses RLS.
alter table movies enable row level security;
alter table people enable row level security;
alter table genres enable row level security;
alter table credits enable row level security;
alter table movie_genres enable row level security;

create policy "movies are publicly readable" on movies for select using (true);
create policy "people are publicly readable" on people for select using (true);
create policy "genres are publicly readable" on genres for select using (true);
create policy "credits are publicly readable" on credits for select using (true);
create policy "movie_genres are publicly readable" on movie_genres for select using (true);
